package by.bsac.timetable.hibernateFiles.entity;
// Generated May 15, 2017 12:08:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import components.IName;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable, Cloneable, IName {

	private static final long serialVersionUID = 1L;

	private short idSubject;
	private Chair chair;
	private String nameSubject;
	private byte eduLevel;
	private String abnameSubject;

	private Set<?> records = new HashSet<Object>(0);

	public Subject() {
	}

	public Subject(short idSubject, Chair chair, String nameSubject, byte eduLevel, String abnameSubject) {
		this.idSubject = idSubject;
		this.chair = chair;
		this.nameSubject = nameSubject;
		this.eduLevel = eduLevel;
		this.abnameSubject = abnameSubject;
	}

	public Subject(Chair chair, String nameSubject, byte eduLevel) {
		this.chair = chair;
		this.nameSubject = nameSubject;
		this.eduLevel = eduLevel;
	}

	public Subject(Chair chair, String nameSubject, byte eduLevel, String abnameSubject) {
		this.chair = chair;
		this.nameSubject = nameSubject;
		this.eduLevel = eduLevel;
		this.abnameSubject = abnameSubject;
	}

	public Subject(short idSubject, Chair chair, String nameSubject, byte eduLevel, String abnameSubject,
			Set<?> records) {
		this.idSubject = idSubject;
		this.chair = chair;
		this.nameSubject = nameSubject;
		this.eduLevel = eduLevel;
		this.abnameSubject = abnameSubject;
		this.records = records;
	}

	public short getIdSubject() {
		return this.idSubject;
	}

	public void setIdSubject(short idSubject) {
		this.idSubject = idSubject;
	}

	public Chair getChair() {
		return this.chair;
	}

	public void setChair(Chair chair) {
		this.chair = chair;
	}

	public String getNameSubject() {
		return this.nameSubject;
	}

	public void setNameSubject(String nameSubject) {
		this.nameSubject = nameSubject;
	}

	public byte getEduLevel() {
		return this.eduLevel;
	}

	public void setEduLevel(byte eduLevel) {
		this.eduLevel = eduLevel;
	}

	public String getAbnameSubject() {
		return this.abnameSubject;
	}

	public void setAbnameSubject(String abnameSubject) {
		this.abnameSubject = abnameSubject;
	}

	public Set<?> getRecords() {
		return this.records;
	}

	public void setRecords(Set<?> records) {
		this.records = records;
	}

	@Override
	public String getName() {
		return this.getNameSubject();
	}

	@Override
	public String toString() {
		return "Subject [idSubject=" + idSubject + ", chair=" + chair + ", nameSubject=" + nameSubject + ", eduLevel="
				+ eduLevel + ", abnameSubject=" + abnameSubject + "]";
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		Subject result = (Subject) super.clone();
		// result.chair = (Chair) chair.clone();
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Subject other = (Subject) obj;

		if (idSubject != other.idSubject)
			return false;
		// if (nameSubject == null) {
		// if (other.nameSubject != null)
		// return false;
		// } else if (!nameSubject.equals(other.nameSubject))
		// return false;
		// if (abnameSubject == null) {
		// if (other.abnameSubject != null)
		// return false;
		// } else if (!abnameSubject.equals(other.abnameSubject))
		// return false;
		// if (chair == null) {
		// if (other.chair != null)
		// return false;
		// } else if (!chair.equals(other.chair))
		// return false;
		// if (eduLevel != other.eduLevel)
		// return false;

		return true;
	}
}