package hibernateFiles.entity;
// Generated May 15, 2017 12:08:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import components.IName;

/**
 * Classroom generated by hbm2java
 */
public class Classroom implements java.io.Serializable, Cloneable, IName {

	private static final long serialVersionUID = 1L;

	private Short idClassroom;
	private short number;
	private byte building;
	private boolean isReserved;

	private Set<?> records = new HashSet<Object>(0);

	public Classroom() {
	}

	public Classroom(short number, byte building) {
		this.number = number;
		this.building = building;
	}

	public Classroom(short number, byte building, Set<?> records) {
		this.number = number;
		this.building = building;
		this.records = records;
	}

	public Short getIdClassroom() {
		return this.idClassroom;
	}

	public void setIdClassroom(Short idClassroom) {
		this.idClassroom = idClassroom;
	}

	public short getNumber() {
		return this.number;
	}

	public void setNumber(short number) {
		this.number = number;
	}

	public byte getBuilding() {
		return this.building;
	}

	public void setBuilding(byte building) {
		this.building = building;
	}

	public Set<?> getRecords() {
		return this.records;
	}

	public void setRecords(Set<?> records) {
		this.records = records;
	}

	public String getFullClassroomName() {
		String format = "%s (%s)";

		String result = String.format(format, this.getNumber(), this.getBuilding());
		return result;
	}

	@Override
	public String getName() {
		return getFullClassroomName();
	}

	public boolean isReserved() {
		return isReserved;
	}

	public void setReserved(boolean isReserved) {
		this.isReserved = isReserved;
	}

	@Override
	public String toString() {
		return "Classroom [idClassroom=" + idClassroom + ", number=" + number + ", building=" + building
				+ ", isReserved=" + isReserved + "]";
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + building;
		result = prime * result + ((idClassroom == null) ? 0 : idClassroom.hashCode());
		result = prime * result + (isReserved ? 1231 : 1237);
		result = prime * result + number;
		result = prime * result + ((records == null) ? 0 : records.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Classroom other = (Classroom) obj;
		if (idClassroom == null) {
			if (other.idClassroom != null)
				return false;
		} else if (!idClassroom.equals(other.idClassroom))
			return false;
		return true;
	}
}