package hibernateFiles.entity;
// Generated May 15, 2017 12:08:05 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SubjectType generated by hbm2java
 */
public class SubjectType implements java.io.Serializable, Cloneable {

	private static final long serialVersionUID = 1L;

	private Byte id;
	private String name;
	private Set<?> records = new HashSet<Object>(0);

	public SubjectType() {
	}

	public SubjectType(String name) {
		this.name = name;
	}

	public SubjectType(String name, Set<?> records) {
		this.name = name;
		this.records = records;
	}

	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<?> getRecords() {
		return this.records;
	}

	public void setRecords(Set<?> records) {
		this.records = records;
	}

	@Override
	public String toString() {
		return "SubjectType [id=" + id + ", name=" + name + "]";
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}

}
